### ISSUE TITLE
zsh completion doesn’t handle the `fly` alias

### ISSUE THREAD

**Issue by chris-morgan** [superfly/flyctl#1845]
If you follow the `flyctl completion zsh --help` instructions to set up completion on zsh, you’ll get completion for `flyctl`, but it won’t work for `fly`, which is customarily symlinked to `flyctl`.

A workaround for this is to add this to your zshrc:

    compdef _flyctl fly

I do not know if this is the best way of doing things. Symlinking _fly → _flyctl in the zsh site-functions directory doesn’t work. I imagine there’s some small stub _fly file that you could generate that would take care of it, but I haven’t poked or prodded. It’s certainly going to complicate the instructions at best, *possibly* make it worth having the program generate the files (especially in light of #1233) rather than emit to stdout and get the user to pipe that to the corresponding file.

If `fly` was a shell alias rather than a symlink, everything would work fine with no extra fuss, but it’s not and largely shouldn’t and can’t be, but I figured it was worth mentioning. But zsh doesn’t do anything about completing on symlinks unless you tell it to (perhaps because with symlinks the different names could do different things).

I suspect this will affect other shells as well, but don’t know. I suggest someone that uses them check and potentially broaden the scope of this issue.

**Comment by yavorski** [comment]
It is not working with `bash` either.

**Comment by grgar** [comment]
Fixed in #4015 but keyword missing in PR to close this issue

**Comment by tomr-a5** [comment]
Thanks for reporting this. #4015 made shell completion use the actual executable name, so both `fly` and `flyctl` generate completion for the name being run. I am going to close this as fixed. Please reopen if completion still fails for `fly` on the latest flyctl.
